// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/interchain_swap/v1/packet.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/anypb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Type defines a classification of swap messages
type SwapMessageType int32

const (
	// Default zero value enumeration
	UNSPECIFIED          SwapMessageType = 0
	MAKE_POOL            SwapMessageType = 1
	TAKE_POOL            SwapMessageType = 2
	CANCEL_POOL          SwapMessageType = 3
	SINGLE_DEPOSIT       SwapMessageType = 4
	MAKE_MULTI_DEPOSIT   SwapMessageType = 5
	CANCEL_MULTI_DEPOSIT SwapMessageType = 6
	TAKE_MULTI_DEPOSIT   SwapMessageType = 7
	MULTI_WITHDRAW       SwapMessageType = 8
	LEFT_SWAP            SwapMessageType = 9
	RIGHT_SWAP           SwapMessageType = 10
)

var SwapMessageType_name = map[int32]string{
	0:  "TYPE_UNSPECIFIED",
	1:  "TYPE_MAKE_POOL",
	2:  "TYPE_TAKE_POOL",
	3:  "TYPE_CANCEL_POOL",
	4:  "TYPE_SINGLE_DEPOSIT",
	5:  "TYPE_MAKE_MULTI_DEPOSIT",
	6:  "TYPE_CANCEL_MULTI_DEPOSIT",
	7:  "TYPE_TAKE_MULTI_DEPOSIT",
	8:  "TYPE_MULTI_WITHDRAW",
	9:  "TYPE_LEFT_SWAP",
	10: "TYPE_RIGHT_SWAP",
}

var SwapMessageType_value = map[string]int32{
	"TYPE_UNSPECIFIED":          0,
	"TYPE_MAKE_POOL":            1,
	"TYPE_TAKE_POOL":            2,
	"TYPE_CANCEL_POOL":          3,
	"TYPE_SINGLE_DEPOSIT":       4,
	"TYPE_MAKE_MULTI_DEPOSIT":   5,
	"TYPE_CANCEL_MULTI_DEPOSIT": 6,
	"TYPE_TAKE_MULTI_DEPOSIT":   7,
	"TYPE_MULTI_WITHDRAW":       8,
	"TYPE_LEFT_SWAP":            9,
	"TYPE_RIGHT_SWAP":           10,
}

func (x SwapMessageType) String() string {
	return proto.EnumName(SwapMessageType_name, int32(x))
}

func (SwapMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23c8ddc04cfb119f, []int{0}
}

type StateChange struct {
	In                  []*types.Coin `protobuf:"bytes,1,rep,name=in,proto3" json:"in,omitempty"`
	Out                 []*types.Coin `protobuf:"bytes,2,rep,name=out,proto3" json:"out,omitempty"`
	PoolTokens          []*types.Coin `protobuf:"bytes,3,rep,name=poolTokens,proto3" json:"poolTokens,omitempty"`
	PoolId              string        `protobuf:"bytes,4,opt,name=poolId,proto3" json:"poolId,omitempty"`
	MultiDepositOrderId string        `protobuf:"bytes,5,opt,name=multiDepositOrderId,proto3" json:"multiDepositOrderId,omitempty"`
	SourceChainId       string        `protobuf:"bytes,6,opt,name=sourceChainId,proto3" json:"sourceChainId,omitempty"`
}

func (m *StateChange) Reset()         { *m = StateChange{} }
func (m *StateChange) String() string { return proto.CompactTextString(m) }
func (*StateChange) ProtoMessage()    {}
func (*StateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_23c8ddc04cfb119f, []int{0}
}
func (m *StateChange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StateChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StateChange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StateChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateChange.Merge(m, src)
}
func (m *StateChange) XXX_Size() int {
	return m.Size()
}
func (m *StateChange) XXX_DiscardUnknown() {
	xxx_messageInfo_StateChange.DiscardUnknown(m)
}

var xxx_messageInfo_StateChange proto.InternalMessageInfo

func (m *StateChange) GetIn() []*types.Coin {
	if m != nil {
		return m.In
	}
	return nil
}

func (m *StateChange) GetOut() []*types.Coin {
	if m != nil {
		return m.Out
	}
	return nil
}

func (m *StateChange) GetPoolTokens() []*types.Coin {
	if m != nil {
		return m.PoolTokens
	}
	return nil
}

func (m *StateChange) GetPoolId() string {
	if m != nil {
		return m.PoolId
	}
	return ""
}

func (m *StateChange) GetMultiDepositOrderId() string {
	if m != nil {
		return m.MultiDepositOrderId
	}
	return ""
}

func (m *StateChange) GetSourceChainId() string {
	if m != nil {
		return m.SourceChainId
	}
	return ""
}

// IBCSwapPacketData is comprised of a raw transaction, type of transaction and optional memo field.
type IBCSwapPacketData struct {
	Type SwapMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=ibc.applications.interchain_swap.v1.SwapMessageType" json:"type,omitempty"`
	// marshall data of transactions
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// current pool states on source chain, could be empty.
	StateChange *StateChange `protobuf:"bytes,3,opt,name=stateChange,proto3" json:"stateChange,omitempty"`
	Memo        string       `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (m *IBCSwapPacketData) Reset()         { *m = IBCSwapPacketData{} }
func (m *IBCSwapPacketData) String() string { return proto.CompactTextString(m) }
func (*IBCSwapPacketData) ProtoMessage()    {}
func (*IBCSwapPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_23c8ddc04cfb119f, []int{1}
}
func (m *IBCSwapPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IBCSwapPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IBCSwapPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IBCSwapPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IBCSwapPacketData.Merge(m, src)
}
func (m *IBCSwapPacketData) XXX_Size() int {
	return m.Size()
}
func (m *IBCSwapPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_IBCSwapPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_IBCSwapPacketData proto.InternalMessageInfo

func (m *IBCSwapPacketData) GetType() SwapMessageType {
	if m != nil {
		return m.Type
	}
	return UNSPECIFIED
}

func (m *IBCSwapPacketData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *IBCSwapPacketData) GetStateChange() *StateChange {
	if m != nil {
		var data StateChange
		ModuleCdc.UnmarshalJSON(m.StateChange, &data);
		return &data
	}
	return nil
}

func (m *IBCSwapPacketData) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func init() {
	proto.RegisterEnum("ibc.applications.interchain_swap.v1.SwapMessageType", SwapMessageType_name, SwapMessageType_value)
	proto.RegisterType((*StateChange)(nil), "ibc.applications.interchain_swap.v1.StateChange")
	proto.RegisterType((*IBCSwapPacketData)(nil), "ibc.applications.interchain_swap.v1.IBCSwapPacketData")
}

func init() {
	proto.RegisterFile("ibc/applications/interchain_swap/v1/packet.proto", fileDescriptor_23c8ddc04cfb119f)
}

var fileDescriptor_23c8ddc04cfb119f = []byte{
	// 676 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcf, 0x4e, 0xdb, 0x4a,
	0x18, 0xc5, 0xe3, 0x24, 0xe4, 0x5e, 0x26, 0x97, 0x90, 0x3b, 0x20, 0x6a, 0xbc, 0xb0, 0x5c, 0x68,
	0xa5, 0xb4, 0x08, 0x3b, 0x81, 0xaa, 0x55, 0x97, 0x21, 0x31, 0x60, 0x35, 0x90, 0xc8, 0x31, 0x42,
	0xed, 0x26, 0x1a, 0x3b, 0x53, 0x33, 0x22, 0xf1, 0x58, 0x99, 0x09, 0x88, 0x37, 0xa8, 0xb2, 0xe2,
	0x05, 0xb2, 0xea, 0xcb, 0x74, 0xc9, 0xb2, 0xdd, 0x55, 0xf0, 0x02, 0x7d, 0x84, 0xca, 0xe3, 0xc8,
	0x49, 0x00, 0x09, 0x76, 0xdf, 0x9c, 0xef, 0x77, 0xe6, 0xcc, 0x3f, 0x0d, 0x28, 0x13, 0xd7, 0x33,
	0x50, 0x18, 0xf6, 0x88, 0x87, 0x38, 0xa1, 0x01, 0x33, 0x48, 0xc0, 0xf1, 0xc0, 0x3b, 0x43, 0x24,
	0xe8, 0xb0, 0x4b, 0x14, 0x1a, 0x17, 0x15, 0x23, 0x44, 0xde, 0x39, 0xe6, 0x7a, 0x38, 0xa0, 0x9c,
	0xc2, 0x4d, 0xe2, 0x7a, 0xfa, 0xac, 0x43, 0xbf, 0xe7, 0xd0, 0x2f, 0x2a, 0xca, 0xba, 0x4f, 0xa9,
	0xdf, 0xc3, 0x86, 0xb0, 0xb8, 0xc3, 0xaf, 0x06, 0x0a, 0xae, 0x62, 0xbf, 0xb2, 0xea, 0x53, 0x9f,
	0x8a, 0xd2, 0x88, 0xaa, 0x89, 0xaa, 0x7a, 0x94, 0xf5, 0x29, 0x33, 0x5c, 0xc4, 0xb0, 0x71, 0x51,
	0x71, 0x31, 0x47, 0x15, 0xc3, 0xa3, 0x24, 0x88, 0xfb, 0x1b, 0xd7, 0x69, 0x90, 0x6f, 0x73, 0xc4,
	0x71, 0xed, 0x0c, 0x05, 0x3e, 0x86, 0x6f, 0x40, 0x9a, 0x04, 0xb2, 0xa4, 0x65, 0x4a, 0xf9, 0x9d,
	0x75, 0x3d, 0x36, 0xeb, 0x91, 0x59, 0x9f, 0x98, 0xf5, 0x1a, 0x25, 0x81, 0x9d, 0x26, 0x01, 0xdc,
	0x02, 0x19, 0x3a, 0xe4, 0x72, 0xfa, 0x29, 0x36, 0xa2, 0xe0, 0x47, 0x00, 0x42, 0x4a, 0x7b, 0x0e,
	0x3d, 0xc7, 0x01, 0x93, 0x33, 0x4f, 0x79, 0x66, 0x60, 0xb8, 0x06, 0x72, 0xd1, 0xc8, 0xea, 0xca,
	0x59, 0x4d, 0x2a, 0x2d, 0xda, 0x93, 0x11, 0x2c, 0x83, 0x95, 0xfe, 0xb0, 0xc7, 0x49, 0x1d, 0x87,
	0x94, 0x11, 0xde, 0x1c, 0x74, 0xf1, 0xc0, 0xea, 0xca, 0x0b, 0x02, 0x7a, 0xac, 0x05, 0x5f, 0x81,
	0x25, 0x46, 0x87, 0x03, 0x2f, 0xda, 0x2c, 0x09, 0xac, 0xae, 0x9c, 0x13, 0xec, 0xbc, 0xb8, 0xf1,
	0x4b, 0x02, 0xff, 0x5b, 0x7b, 0xb5, 0xf6, 0x25, 0x0a, 0x5b, 0xe2, 0x82, 0xea, 0x88, 0x23, 0x78,
	0x08, 0xb2, 0xfc, 0x2a, 0xc4, 0xb2, 0xa4, 0x49, 0xa5, 0xc2, 0xce, 0x3b, 0xfd, 0x19, 0xb7, 0xa5,
	0x47, 0x53, 0x1c, 0x61, 0xc6, 0x90, 0x8f, 0x9d, 0xab, 0x10, 0xdb, 0x62, 0x06, 0x08, 0x41, 0xb6,
	0x8b, 0x38, 0x92, 0xd3, 0x9a, 0x54, 0xfa, 0xcf, 0x16, 0x35, 0xb4, 0x41, 0x9e, 0x4d, 0x6f, 0x41,
	0xce, 0x68, 0x52, 0x29, 0xbf, 0x53, 0x7e, 0x5e, 0xc8, 0xd4, 0x67, 0xcf, 0x4e, 0x12, 0xe5, 0xf4,
	0x71, 0x9f, 0x4e, 0x4e, 0x4d, 0xd4, 0x6f, 0xff, 0x64, 0xc0, 0xf2, 0xbd, 0x55, 0xc1, 0xd7, 0xa0,
	0xe8, 0x7c, 0x6e, 0x99, 0x9d, 0x93, 0xe3, 0x76, 0xcb, 0xac, 0x59, 0xfb, 0x96, 0x59, 0x2f, 0xa6,
	0x94, 0xe5, 0xd1, 0x58, 0xcb, 0xcf, 0x48, 0xf0, 0x25, 0x28, 0x08, 0xec, 0xa8, 0xfa, 0xc9, 0xec,
	0xb4, 0x9a, 0xcd, 0x46, 0x51, 0x52, 0x96, 0x46, 0x63, 0x6d, 0x31, 0x11, 0x12, 0xc4, 0x49, 0x90,
	0x74, 0x8c, 0x24, 0x42, 0x12, 0x56, 0xab, 0x1e, 0xd7, 0xcc, 0x46, 0x0c, 0x65, 0xe2, 0xb0, 0x19,
	0x09, 0x6e, 0x81, 0x15, 0x81, 0xb5, 0xad, 0xe3, 0x83, 0x86, 0xd9, 0xa9, 0x9b, 0xad, 0x66, 0xdb,
	0x72, 0x8a, 0x59, 0x05, 0x8e, 0xc6, 0x5a, 0x61, 0x5e, 0x85, 0xbb, 0xe0, 0xc5, 0x74, 0x65, 0x47,
	0x27, 0x0d, 0xc7, 0x4a, 0x0c, 0x0b, 0xca, 0xda, 0x68, 0xac, 0xc1, 0x87, 0x1d, 0xf8, 0x01, 0xac,
	0xcf, 0x2e, 0x64, 0xde, 0x96, 0x53, 0xe4, 0xd1, 0x58, 0x5b, 0x7d, 0xac, 0x97, 0xa4, 0x39, 0x0f,
	0xd3, 0xfe, 0x89, 0xd3, 0x1e, 0x76, 0x92, 0xfd, 0xc4, 0xea, 0xa9, 0xe5, 0x1c, 0xd6, 0xed, 0xea,
	0x69, 0xf1, 0xdf, 0x78, 0x3f, 0xf3, 0x6a, 0x72, 0x8c, 0x0d, 0x73, 0xdf, 0xe9, 0xb4, 0x4f, 0xab,
	0xad, 0xe2, 0x62, 0x7c, 0x8c, 0x89, 0x00, 0x37, 0xc1, 0xb2, 0x40, 0x6c, 0xeb, 0xe0, 0x70, 0xc2,
	0x00, 0xa5, 0x30, 0x1a, 0x6b, 0x60, 0xaa, 0x28, 0xd9, 0x6f, 0xdf, 0xd5, 0xd4, 0x9e, 0xf7, 0xe3,
	0x56, 0x95, 0x6e, 0x6e, 0x55, 0xe9, 0xf7, 0xad, 0x2a, 0x5d, 0xdf, 0xa9, 0xa9, 0x9b, 0x3b, 0x35,
	0xf5, 0xf3, 0x4e, 0x4d, 0x7d, 0xb1, 0x7c, 0xc2, 0xcf, 0x86, 0xae, 0xee, 0xd1, 0xbe, 0xc1, 0x48,
	0x17, 0x8b, 0x1f, 0xc1, 0xa3, 0x3d, 0x83, 0xb8, 0x5e, 0xfc, 0x45, 0xbd, 0x37, 0xfa, 0xb4, 0x3b,
	0xec, 0x61, 0x16, 0x7d, 0x65, 0xcc, 0xa8, 0x94, 0x2b, 0xdb, 0xd3, 0x17, 0xb8, 0x2d, 0x98, 0xe8,
	0x49, 0x33, 0x37, 0x27, 0xbc, 0xbb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x20, 0x57, 0x61, 0xe2,
	0xf7, 0x04, 0x00, 0x00,
}

func (m *StateChange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StateChange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StateChange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SourceChainId) > 0 {
		i -= len(m.SourceChainId)
		copy(dAtA[i:], m.SourceChainId)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.SourceChainId)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.MultiDepositOrderId) > 0 {
		i -= len(m.MultiDepositOrderId)
		copy(dAtA[i:], m.MultiDepositOrderId)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.MultiDepositOrderId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.PoolId) > 0 {
		i -= len(m.PoolId)
		copy(dAtA[i:], m.PoolId)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.PoolId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PoolTokens) > 0 {
		for iNdEx := len(m.PoolTokens) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PoolTokens[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPacket(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Out) > 0 {
		for iNdEx := len(m.Out) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Out[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPacket(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.In) > 0 {
		for iNdEx := len(m.In) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.In[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPacket(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *IBCSwapPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IBCSwapPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IBCSwapPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x22
	}
	if m.StateChange != nil {
		{
			var data StateChange
			ModuleCdc.UnmarshalJSON(m.StateChange, &data);
			size, err := data.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if m.Type != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPacket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StateChange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.In) > 0 {
		for _, e := range m.In {
			l = e.Size()
			n += 1 + l + sovPacket(uint64(l))
		}
	}
	if len(m.Out) > 0 {
		for _, e := range m.Out {
			l = e.Size()
			n += 1 + l + sovPacket(uint64(l))
		}
	}
	if len(m.PoolTokens) > 0 {
		for _, e := range m.PoolTokens {
			l = e.Size()
			n += 1 + l + sovPacket(uint64(l))
		}
	}
	l = len(m.PoolId)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.MultiDepositOrderId)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.SourceChainId)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *IBCSwapPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovPacket(uint64(m.Type))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	if m.StateChange != nil {
		var data StateChange
		ModuleCdc.UnmarshalJSON(m.StateChange, &data);
		l = data.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func sovPacket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPacket(x uint64) (n int) {
	return sovPacket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StateChange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StateChange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StateChange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field In", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.In = append(m.In, &types.Coin{})
			if err := m.In[len(m.In)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Out", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Out = append(m.Out, &types.Coin{})
			if err := m.Out[len(m.Out)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolTokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolTokens = append(m.PoolTokens, &types.Coin{})
			if err := m.PoolTokens[len(m.PoolTokens)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultiDepositOrderId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MultiDepositOrderId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IBCSwapPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IBCSwapPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IBCSwapPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= SwapMessageType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateChange", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StateChange == nil {
				m.StateChange = []byte{}
			}
			var data StateChange
			ModuleCdc.UnmarshalJSON(m.StateChange, &data);
			if err := data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPacket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPacket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPacket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPacket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
