// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/atomic_swap/v1/swap.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// OTC
type Status int32

const (
	Status_INITIAL  Status = 0
	Status_SYNC     Status = 1
	Status_CANCEL   Status = 2
	Status_COMPLETE Status = 3
)

var Status_name = map[int32]string{
	0: "INITIAL",
	1: "SYNC",
	2: "CANCEL",
	3: "COMPLETE",
}

var Status_value = map[string]int32{
	"INITIAL":  0,
	"SYNC":     1,
	"CANCEL":   2,
	"COMPLETE": 3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ab3ff4471e3e52b, []int{0}
}

// Params defines the set of IBC swap parameters.
type Params struct {
	// swap_enabled enables or disables all cross-chain token transfers from this chain.
	SwapEnabled bool `protobuf:"varint,1,opt,name=swap_enabled,json=swapEnabled,proto3" json:"swap_enabled,omitempty" yaml:"swap_enabled"`
	// max_fee_rate set a max value of fee, it's base point, 1/10000
	MaxFeeRate uint32 `protobuf:"varint,2,opt,name=max_fee_rate,json=maxFeeRate,proto3" json:"max_fee_rate,omitempty" yaml:"max_fee_rate"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ab3ff4471e3e52b, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSwapEnabled() bool {
	if m != nil {
		return m.SwapEnabled
	}
	return false
}

func (m *Params) GetMaxFeeRate() uint32 {
	if m != nil {
		return m.MaxFeeRate
	}
	return 0
}

type SwapMaker struct {
	// the port on which the packet will be sent
	SourcePort string `protobuf:"bytes,1,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty" yaml:"source_port"`
	// the channel by which the packet will be sent
	SourceChannel string `protobuf:"bytes,2,opt,name=source_channel,json=sourceChannel,proto3" json:"source_channel,omitempty" yaml:"source_channel"`
	// the tokens to be sell
	SellToken types.Coin `protobuf:"bytes,3,opt,name=sell_token,json=sellToken,proto3" json:"sell_token"`
	BuyToken  types.Coin `protobuf:"bytes,4,opt,name=buy_token,json=buyToken,proto3" json:"buy_token"`
	// the sender address
	MakerAddress string `protobuf:"bytes,5,opt,name=maker_address,json=makerAddress,proto3" json:"maker_address,omitempty" yaml:"maker_address"`
	// the sender's address on the destination chain
	MakerReceivingAddress string `protobuf:"bytes,6,opt,name=maker_receiving_address,json=makerReceivingAddress,proto3" json:"maker_receiving_address,omitempty" yaml:"maker_receiving_address"`
	// if desired_taker is specified,
	// only the desired_taker is allowed to take this order
	// this is address on destination chain
	DesiredTaker    string `protobuf:"bytes,7,opt,name=desired_taker,json=desiredTaker,proto3" json:"desired_taker,omitempty"`
	CreateTimestamp int64  `protobuf:"varint,8,opt,name=create_timestamp,json=createTimestamp,proto3" json:"create_timestamp,omitempty"`
}

func (m *SwapMaker) Reset()         { *m = SwapMaker{} }
func (m *SwapMaker) String() string { return proto.CompactTextString(m) }
func (*SwapMaker) ProtoMessage()    {}
func (*SwapMaker) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ab3ff4471e3e52b, []int{1}
}
func (m *SwapMaker) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SwapMaker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SwapMaker.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SwapMaker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapMaker.Merge(m, src)
}
func (m *SwapMaker) XXX_Size() int {
	return m.Size()
}
func (m *SwapMaker) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapMaker.DiscardUnknown(m)
}

var xxx_messageInfo_SwapMaker proto.InternalMessageInfo

func (m *SwapMaker) GetSourcePort() string {
	if m != nil {
		return m.SourcePort
	}
	return ""
}

func (m *SwapMaker) GetSourceChannel() string {
	if m != nil {
		return m.SourceChannel
	}
	return ""
}

func (m *SwapMaker) GetSellToken() types.Coin {
	if m != nil {
		return m.SellToken
	}
	return types.Coin{}
}

func (m *SwapMaker) GetBuyToken() types.Coin {
	if m != nil {
		return m.BuyToken
	}
	return types.Coin{}
}

func (m *SwapMaker) GetMakerAddress() string {
	if m != nil {
		return m.MakerAddress
	}
	return ""
}

func (m *SwapMaker) GetMakerReceivingAddress() string {
	if m != nil {
		return m.MakerReceivingAddress
	}
	return ""
}

func (m *SwapMaker) GetDesiredTaker() string {
	if m != nil {
		return m.DesiredTaker
	}
	return ""
}

func (m *SwapMaker) GetCreateTimestamp() int64 {
	if m != nil {
		return m.CreateTimestamp
	}
	return 0
}

type SwapTaker struct {
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// the tokens to be sell
	SellToken types.Coin `protobuf:"bytes,2,opt,name=sell_token,json=sellToken,proto3" json:"sell_token"`
	// the sender address
	TakerAddress string `protobuf:"bytes,3,opt,name=taker_address,json=takerAddress,proto3" json:"taker_address,omitempty" yaml:"taker_address"`
	// the sender's address on the destination chain
	TakerReceivingAddress string `protobuf:"bytes,4,opt,name=taker_receiving_address,json=takerReceivingAddress,proto3" json:"taker_receiving_address,omitempty" yaml:"taker_receiving_address"`
	CreateTimestamp       int64  `protobuf:"varint,5,opt,name=create_timestamp,json=createTimestamp,proto3" json:"create_timestamp,omitempty"`
}

func (m *SwapTaker) Reset()         { *m = SwapTaker{} }
func (m *SwapTaker) String() string { return proto.CompactTextString(m) }
func (*SwapTaker) ProtoMessage()    {}
func (*SwapTaker) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ab3ff4471e3e52b, []int{2}
}
func (m *SwapTaker) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SwapTaker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SwapTaker.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SwapTaker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapTaker.Merge(m, src)
}
func (m *SwapTaker) XXX_Size() int {
	return m.Size()
}
func (m *SwapTaker) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapTaker.DiscardUnknown(m)
}

var xxx_messageInfo_SwapTaker proto.InternalMessageInfo

func (m *SwapTaker) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *SwapTaker) GetSellToken() types.Coin {
	if m != nil {
		return m.SellToken
	}
	return types.Coin{}
}

func (m *SwapTaker) GetTakerAddress() string {
	if m != nil {
		return m.TakerAddress
	}
	return ""
}

func (m *SwapTaker) GetTakerReceivingAddress() string {
	if m != nil {
		return m.TakerReceivingAddress
	}
	return ""
}

func (m *SwapTaker) GetCreateTimestamp() int64 {
	if m != nil {
		return m.CreateTimestamp
	}
	return 0
}

type AtomicSwapOrder struct {
	Id                string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Maker             *SwapMaker `protobuf:"bytes,2,opt,name=maker,proto3" json:"maker,omitempty"`
	Status            Status     `protobuf:"varint,3,opt,name=status,proto3,enum=ibc.applications.atomic_swap.v1.Status" json:"status,omitempty"`
	ChannelId         string     `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Takers            *SwapTaker `protobuf:"bytes,5,opt,name=takers,proto3" json:"takers,omitempty"`
	CancelTimestamp   int64      `protobuf:"varint,7,opt,name=cancel_timestamp,json=cancelTimestamp,proto3" json:"cancel_timestamp,omitempty"`
	CompleteTimestamp int64      `protobuf:"varint,8,opt,name=complete_timestamp,json=completeTimestamp,proto3" json:"complete_timestamp,omitempty"`
}

func (m *AtomicSwapOrder) Reset()         { *m = AtomicSwapOrder{} }
func (m *AtomicSwapOrder) String() string { return proto.CompactTextString(m) }
func (*AtomicSwapOrder) ProtoMessage()    {}
func (*AtomicSwapOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ab3ff4471e3e52b, []int{3}
}
func (m *AtomicSwapOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AtomicSwapOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AtomicSwapOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AtomicSwapOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AtomicSwapOrder.Merge(m, src)
}
func (m *AtomicSwapOrder) XXX_Size() int {
	return m.Size()
}
func (m *AtomicSwapOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_AtomicSwapOrder.DiscardUnknown(m)
}

var xxx_messageInfo_AtomicSwapOrder proto.InternalMessageInfo

func (m *AtomicSwapOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AtomicSwapOrder) GetMaker() *SwapMaker {
	if m != nil {
		return m.Maker
	}
	return nil
}

func (m *AtomicSwapOrder) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_INITIAL
}

func (m *AtomicSwapOrder) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *AtomicSwapOrder) GetTakers() *SwapTaker {
	if m != nil {
		return m.Takers
	}
	return nil
}

func (m *AtomicSwapOrder) GetCancelTimestamp() int64 {
	if m != nil {
		return m.CancelTimestamp
	}
	return 0
}

func (m *AtomicSwapOrder) GetCompleteTimestamp() int64 {
	if m != nil {
		return m.CompleteTimestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("ibc.applications.atomic_swap.v1.Status", Status_name, Status_value)
	proto.RegisterType((*Params)(nil), "ibc.applications.atomic_swap.v1.Params")
	proto.RegisterType((*SwapMaker)(nil), "ibc.applications.atomic_swap.v1.SwapMaker")
	proto.RegisterType((*SwapTaker)(nil), "ibc.applications.atomic_swap.v1.SwapTaker")
	proto.RegisterType((*AtomicSwapOrder)(nil), "ibc.applications.atomic_swap.v1.AtomicSwapOrder")
}

func init() {
	proto.RegisterFile("ibc/applications/atomic_swap/v1/swap.proto", fileDescriptor_7ab3ff4471e3e52b)
}

var fileDescriptor_7ab3ff4471e3e52b = []byte{
	// 778 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xdf, 0x8e, 0xda, 0x46,
	0x14, 0xc6, 0x31, 0xec, 0xf2, 0xe7, 0x00, 0x1b, 0x3a, 0x4d, 0x1a, 0x36, 0x52, 0x0d, 0x72, 0x2f,
	0x4a, 0x57, 0x8a, 0x1d, 0xd2, 0x4a, 0x55, 0xa2, 0xa6, 0x5d, 0x40, 0x54, 0x42, 0xda, 0x6c, 0x56,
	0x13, 0x6e, 0xba, 0x37, 0xd6, 0xd8, 0x9e, 0x12, 0x2b, 0xb6, 0xc7, 0xf2, 0x0c, 0x64, 0xb9, 0xea,
	0x2b, 0xf4, 0x41, 0xfa, 0x20, 0xb9, 0xcc, 0x65, 0xaf, 0x50, 0xbb, 0xfb, 0x00, 0x95, 0x78, 0x82,
	0xca, 0x33, 0x86, 0x3a, 0x94, 0x68, 0x93, 0x2b, 0x73, 0xce, 0x77, 0xbe, 0xa3, 0xc3, 0xef, 0xcc,
	0x0c, 0x9c, 0xf8, 0x8e, 0x6b, 0x91, 0x38, 0x0e, 0x7c, 0x97, 0x08, 0x9f, 0x45, 0xdc, 0x22, 0x82,
	0x85, 0xbe, 0x6b, 0xf3, 0x37, 0x24, 0xb6, 0x16, 0x7d, 0x2b, 0xfd, 0x9a, 0x71, 0xc2, 0x04, 0x43,
	0x1d, 0xdf, 0x71, 0xcd, 0x7c, 0xad, 0x99, 0xab, 0x35, 0x17, 0xfd, 0x07, 0x77, 0x67, 0x6c, 0xc6,
	0x64, 0xad, 0x95, 0xfe, 0x52, 0xb6, 0x07, 0xba, 0xcb, 0x78, 0xc8, 0xb8, 0xe5, 0x10, 0x4e, 0xad,
	0x45, 0xdf, 0xa1, 0x82, 0xf4, 0x2d, 0x97, 0xf9, 0x51, 0xa6, 0xf7, 0x6e, 0x1b, 0x41, 0x5c, 0xa9,
	0x4a, 0xe3, 0x37, 0x28, 0x5f, 0x90, 0x84, 0x84, 0x1c, 0x3d, 0x85, 0x46, 0xaa, 0xda, 0x34, 0x22,
	0x4e, 0x40, 0xbd, 0xb6, 0xd6, 0xd5, 0x7a, 0xd5, 0xe1, 0xfd, 0xf5, 0xaa, 0xf3, 0xf9, 0x92, 0x84,
	0xc1, 0x53, 0x23, 0xaf, 0x1a, 0xb8, 0x9e, 0x86, 0x63, 0x15, 0xa1, 0x27, 0xd0, 0x08, 0xc9, 0x95,
	0xfd, 0x2b, 0xa5, 0x76, 0x42, 0x04, 0x6d, 0x17, 0xbb, 0x5a, 0xaf, 0x99, 0xf7, 0xe6, 0x55, 0x03,
	0x43, 0x48, 0xae, 0x7e, 0xa6, 0x14, 0xa7, 0xc1, 0x3f, 0x25, 0xa8, 0xbd, 0x7c, 0x43, 0xe2, 0xe7,
	0xe4, 0x35, 0x4d, 0xd0, 0xf7, 0x50, 0xe7, 0x6c, 0x9e, 0xb8, 0xd4, 0x8e, 0x59, 0x22, 0xe4, 0x0c,
	0xb5, 0xe1, 0x17, 0xeb, 0x55, 0x07, 0x65, 0x33, 0xfc, 0x27, 0x1a, 0x18, 0x54, 0x74, 0xc1, 0x12,
	0x81, 0x4e, 0xe1, 0x28, 0xd3, 0xdc, 0x57, 0x24, 0x8a, 0x68, 0x20, 0x67, 0xa8, 0x0d, 0x8f, 0xd7,
	0xab, 0xce, 0xbd, 0xf7, 0xbc, 0x99, 0x6e, 0xe0, 0xa6, 0x4a, 0x8c, 0x54, 0x8c, 0x7e, 0x04, 0xe0,
	0x34, 0x08, 0x6c, 0xc1, 0x5e, 0xd3, 0xa8, 0x5d, 0xea, 0x6a, 0xbd, 0xfa, 0xe3, 0x63, 0x53, 0x81,
	0x36, 0x53, 0xd0, 0x66, 0x06, 0xda, 0x1c, 0x31, 0x3f, 0x1a, 0x1e, 0xbc, 0x5d, 0x75, 0x0a, 0xb8,
	0x96, 0x5a, 0xa6, 0xa9, 0x03, 0xfd, 0x00, 0x35, 0x67, 0xbe, 0xcc, 0xec, 0x07, 0x1f, 0x67, 0xaf,
	0x3a, 0xf3, 0xa5, 0x72, 0x3f, 0x83, 0x66, 0x98, 0x12, 0xb0, 0x89, 0xe7, 0x25, 0x94, 0xf3, 0xf6,
	0xa1, 0x1c, 0xbf, 0xbd, 0x5e, 0x75, 0xee, 0x6e, 0x10, 0xe6, 0x64, 0x03, 0x37, 0x64, 0x3c, 0x50,
	0x21, 0xba, 0x84, 0xfb, 0x4a, 0x4f, 0xa8, 0x4b, 0xfd, 0x85, 0x1f, 0xcd, 0xb6, 0x8d, 0xca, 0xb2,
	0x91, 0xb1, 0x5e, 0x75, 0xf4, 0x7c, 0xa3, 0xff, 0x15, 0x1a, 0xf8, 0x9e, 0x54, 0xf0, 0x46, 0xd8,
	0xf4, 0xfe, 0x0a, 0x9a, 0x1e, 0xe5, 0x7e, 0x42, 0x3d, 0x5b, 0xa4, 0x05, 0xed, 0x4a, 0xda, 0x11,
	0x37, 0xb2, 0xe4, 0x54, 0x2e, 0xee, 0x1b, 0x68, 0xb9, 0x09, 0x25, 0x82, 0xda, 0xc2, 0x0f, 0x29,
	0x17, 0x24, 0x8c, 0xdb, 0xd5, 0xae, 0xd6, 0x2b, 0xe1, 0x3b, 0x2a, 0x3f, 0xdd, 0xa4, 0x8d, 0x3f,
	0x8a, 0x6a, 0xe3, 0xca, 0x78, 0x0c, 0x55, 0x96, 0x78, 0x34, 0xb1, 0x7d, 0x75, 0xe4, 0x6a, 0xb8,
	0x22, 0xe3, 0x89, 0xb7, 0xb3, 0x91, 0xe2, 0x27, 0x6f, 0xe4, 0x19, 0x34, 0xc5, 0x7b, 0x4c, 0x4b,
	0xbb, 0x4c, 0xc5, 0x0e, 0x53, 0xb1, 0xc3, 0x54, 0x7c, 0x80, 0xe9, 0xc1, 0x2e, 0x53, 0xf1, 0x41,
	0xa6, 0x62, 0x2f, 0xd3, 0x7d, 0xb8, 0x0e, 0xf7, 0xe3, 0xfa, 0xbb, 0x08, 0x77, 0x06, 0xf2, 0xf6,
	0xa6, 0xd0, 0x5e, 0xa4, 0x6c, 0xd0, 0x11, 0x14, 0xb7, 0xb8, 0x8a, 0xbe, 0x87, 0x4e, 0xe1, 0x50,
	0xee, 0x2e, 0x83, 0x74, 0x62, 0xde, 0xf2, 0xac, 0x98, 0xdb, 0x1b, 0x87, 0x95, 0x11, 0xfd, 0x04,
	0x65, 0x2e, 0x88, 0x98, 0x2b, 0x48, 0x47, 0x8f, 0xbf, 0xbe, 0xbd, 0x85, 0x2c, 0xc7, 0x99, 0x0d,
	0x7d, 0x09, 0x90, 0xdd, 0xac, 0x74, 0x93, 0x12, 0x10, 0xae, 0x65, 0x99, 0x89, 0x87, 0x86, 0x50,
	0x96, 0x24, 0xd4, 0xc1, 0xfe, 0xd8, 0x11, 0xe5, 0x11, 0xc1, 0x99, 0x53, 0x42, 0x23, 0x91, 0x4b,
	0x83, 0x1c, 0xb4, 0x4a, 0x06, 0x4d, 0xe6, 0xb7, 0xd0, 0xd0, 0x43, 0x40, 0x2e, 0x0b, 0xe3, 0x80,
	0xee, 0x39, 0x90, 0x9f, 0x6d, 0x94, 0x6d, 0xf9, 0xc9, 0x13, 0x28, 0xab, 0xbf, 0x83, 0xea, 0x50,
	0x99, 0x9c, 0x4f, 0xa6, 0x93, 0xc1, 0x59, 0xab, 0x80, 0xaa, 0x70, 0xf0, 0xf2, 0x97, 0xf3, 0x51,
	0x4b, 0x43, 0x00, 0xe5, 0xd1, 0xe0, 0x7c, 0x34, 0x3e, 0x6b, 0x15, 0x51, 0x03, 0xaa, 0xa3, 0x17,
	0xcf, 0x2f, 0xce, 0xc6, 0xd3, 0x71, 0xab, 0x34, 0xbc, 0x7c, 0x7b, 0xad, 0x6b, 0xef, 0xae, 0x75,
	0xed, 0xaf, 0x6b, 0x5d, 0xfb, 0xfd, 0x46, 0x2f, 0xbc, 0xbb, 0xd1, 0x0b, 0x7f, 0xde, 0xe8, 0x85,
	0xcb, 0xd3, 0x99, 0x2f, 0x5e, 0xcd, 0x1d, 0xd3, 0x65, 0xa1, 0xe5, 0x3b, 0xae, 0x7c, 0x7a, 0x37,
	0xdf, 0xc5, 0x77, 0x56, 0xc8, 0xbc, 0x79, 0x40, 0x79, 0xfa, 0x4c, 0x73, 0xab, 0xff, 0xe8, 0xd1,
	0xc3, 0xfc, 0x13, 0x2d, 0x96, 0x31, 0xe5, 0x4e, 0x59, 0xbe, 0xd1, 0xdf, 0xfe, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x8e, 0xea, 0xb8, 0x2c, 0x52, 0x06, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxFeeRate != 0 {
		i = encodeVarintSwap(dAtA, i, uint64(m.MaxFeeRate))
		i--
		dAtA[i] = 0x10
	}
	if m.SwapEnabled {
		i--
		if m.SwapEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SwapMaker) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SwapMaker) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SwapMaker) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreateTimestamp != 0 {
		i = encodeVarintSwap(dAtA, i, uint64(m.CreateTimestamp))
		i--
		dAtA[i] = 0x40
	}
	if len(m.DesiredTaker) > 0 {
		i -= len(m.DesiredTaker)
		copy(dAtA[i:], m.DesiredTaker)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.DesiredTaker)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.MakerReceivingAddress) > 0 {
		i -= len(m.MakerReceivingAddress)
		copy(dAtA[i:], m.MakerReceivingAddress)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.MakerReceivingAddress)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.MakerAddress) > 0 {
		i -= len(m.MakerAddress)
		copy(dAtA[i:], m.MakerAddress)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.MakerAddress)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size, err := m.BuyToken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSwap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.SellToken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSwap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.SourceChannel) > 0 {
		i -= len(m.SourceChannel)
		copy(dAtA[i:], m.SourceChannel)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.SourceChannel)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SourcePort) > 0 {
		i -= len(m.SourcePort)
		copy(dAtA[i:], m.SourcePort)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.SourcePort)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SwapTaker) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SwapTaker) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SwapTaker) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreateTimestamp != 0 {
		i = encodeVarintSwap(dAtA, i, uint64(m.CreateTimestamp))
		i--
		dAtA[i] = 0x28
	}
	if len(m.TakerReceivingAddress) > 0 {
		i -= len(m.TakerReceivingAddress)
		copy(dAtA[i:], m.TakerReceivingAddress)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.TakerReceivingAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TakerAddress) > 0 {
		i -= len(m.TakerAddress)
		copy(dAtA[i:], m.TakerAddress)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.TakerAddress)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.SellToken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSwap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.OrderId) > 0 {
		i -= len(m.OrderId)
		copy(dAtA[i:], m.OrderId)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.OrderId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AtomicSwapOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AtomicSwapOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AtomicSwapOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CompleteTimestamp != 0 {
		i = encodeVarintSwap(dAtA, i, uint64(m.CompleteTimestamp))
		i--
		dAtA[i] = 0x40
	}
	if m.CancelTimestamp != 0 {
		i = encodeVarintSwap(dAtA, i, uint64(m.CancelTimestamp))
		i--
		dAtA[i] = 0x38
	}
	if m.Takers != nil {
		{
			size, err := m.Takers.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSwap(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x22
	}
	if m.Status != 0 {
		i = encodeVarintSwap(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	if m.Maker != nil {
		{
			size, err := m.Maker.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSwap(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSwap(dAtA []byte, offset int, v uint64) int {
	offset -= sovSwap(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SwapEnabled {
		n += 2
	}
	if m.MaxFeeRate != 0 {
		n += 1 + sovSwap(uint64(m.MaxFeeRate))
	}
	return n
}

func (m *SwapMaker) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SourcePort)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	l = len(m.SourceChannel)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	l = m.SellToken.Size()
	n += 1 + l + sovSwap(uint64(l))
	l = m.BuyToken.Size()
	n += 1 + l + sovSwap(uint64(l))
	l = len(m.MakerAddress)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	l = len(m.MakerReceivingAddress)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	l = len(m.DesiredTaker)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	if m.CreateTimestamp != 0 {
		n += 1 + sovSwap(uint64(m.CreateTimestamp))
	}
	return n
}

func (m *SwapTaker) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrderId)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	l = m.SellToken.Size()
	n += 1 + l + sovSwap(uint64(l))
	l = len(m.TakerAddress)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	l = len(m.TakerReceivingAddress)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	if m.CreateTimestamp != 0 {
		n += 1 + sovSwap(uint64(m.CreateTimestamp))
	}
	return n
}

func (m *AtomicSwapOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	if m.Maker != nil {
		l = m.Maker.Size()
		n += 1 + l + sovSwap(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovSwap(uint64(m.Status))
	}
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	if m.Takers != nil {
		l = m.Takers.Size()
		n += 1 + l + sovSwap(uint64(l))
	}
	if m.CancelTimestamp != 0 {
		n += 1 + sovSwap(uint64(m.CancelTimestamp))
	}
	if m.CompleteTimestamp != 0 {
		n += 1 + sovSwap(uint64(m.CompleteTimestamp))
	}
	return n
}

func sovSwap(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSwap(x uint64) (n int) {
	return sovSwap(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSwap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SwapEnabled = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxFeeRate", wireType)
			}
			m.MaxFeeRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxFeeRate |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSwap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSwap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SwapMaker) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSwap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SwapMaker: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SwapMaker: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourcePort", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourcePort = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SellToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BuyToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MakerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerReceivingAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MakerReceivingAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DesiredTaker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DesiredTaker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateTimestamp", wireType)
			}
			m.CreateTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreateTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSwap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSwap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SwapTaker) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSwap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SwapTaker: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SwapTaker: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SellToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TakerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerReceivingAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TakerReceivingAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateTimestamp", wireType)
			}
			m.CreateTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreateTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSwap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSwap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AtomicSwapOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSwap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AtomicSwapOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AtomicSwapOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Maker", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Maker == nil {
				m.Maker = &SwapMaker{}
			}
			if err := m.Maker.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Takers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Takers == nil {
				m.Takers = &SwapTaker{}
			}
			if err := m.Takers.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CancelTimestamp", wireType)
			}
			m.CancelTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CancelTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompleteTimestamp", wireType)
			}
			m.CompleteTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompleteTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSwap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSwap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSwap(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSwap
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSwap
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSwap
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSwap
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSwap        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSwap          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSwap = fmt.Errorf("proto: unexpected end of group")
)
