// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/atomic_swap/v1/swap.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_INITIAL  Status = 0
	Status_SYNC     Status = 1
	Status_CANCEL   Status = 2
	Status_COMPLETE Status = 3
)

var Status_name = map[int32]string{
	0: "INITIAL",
	1: "SYNC",
	2: "CANCEL",
	3: "COMPLETE",
}

var Status_value = map[string]int32{
	"INITIAL":  0,
	"SYNC":     1,
	"CANCEL":   2,
	"COMPLETE": 3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ab3ff4471e3e52b, []int{0}
}

type FillStatus int32

const (
	FillStatus_NONE_FILL     FillStatus = 0
	FillStatus_PARTIAL_FILL  FillStatus = 1
	FillStatus_COMPLETE_FILL FillStatus = 2
)

var FillStatus_name = map[int32]string{
	0: "NONE_FILL",
	1: "PARTIAL_FILL",
	2: "COMPLETE_FILL",
}

var FillStatus_value = map[string]int32{
	"NONE_FILL":     0,
	"PARTIAL_FILL":  1,
	"COMPLETE_FILL": 2,
}

func (x FillStatus) String() string {
	return proto.EnumName(FillStatus_name, int32(x))
}

func (FillStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ab3ff4471e3e52b, []int{1}
}

// Params defines the set of IBC swap parameters.
type Params struct {
	// swap_enabled enables or disables all cross-chain token transfers from this chain.
	SwapEnabled bool `protobuf:"varint,1,opt,name=swap_enabled,json=swapEnabled,proto3" json:"swap_enabled,omitempty" yaml:"swap_enabled"`
	// max_fee_rate set a max value of fee, it's base point, 1/10000
	MaxFeeRate uint32 `protobuf:"varint,2,opt,name=max_fee_rate,json=maxFeeRate,proto3" json:"max_fee_rate,omitempty" yaml:"max_fee_rate"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ab3ff4471e3e52b, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSwapEnabled() bool {
	if m != nil {
		return m.SwapEnabled
	}
	return false
}

func (m *Params) GetMaxFeeRate() uint32 {
	if m != nil {
		return m.MaxFeeRate
	}
	return 0
}

type SwapMaker struct {
	// the port on which the packet will be sent
	SourcePort string `protobuf:"bytes,1,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty" yaml:"source_port"`
	// the channel by which the packet will be sent
	SourceChannel string `protobuf:"bytes,2,opt,name=source_channel,json=sourceChannel,proto3" json:"source_channel,omitempty" yaml:"source_channel"`
	// the tokens to be sell
	SellToken types.Coin `protobuf:"bytes,3,opt,name=sell_token,json=sellToken,proto3" json:"sell_token"`
	BuyToken  types.Coin `protobuf:"bytes,4,opt,name=buy_token,json=buyToken,proto3" json:"buy_token"`
	// the sender address
	MakerAddress string `protobuf:"bytes,5,opt,name=maker_address,json=makerAddress,proto3" json:"maker_address,omitempty" yaml:"maker_address"`
	// the sender's address on the destination chain
	MakerReceivingAddress string `protobuf:"bytes,6,opt,name=maker_receiving_address,json=makerReceivingAddress,proto3" json:"maker_receiving_address,omitempty" yaml:"maker_receiving_address"`
	// if desired_taker is specified,
	// only the desired_taker is allowed to take this order
	// this is address on destination chain
	DesiredTaker    string `protobuf:"bytes,7,opt,name=desired_taker,json=desiredTaker,proto3" json:"desired_taker,omitempty"`
	CreateTimestamp int64  `protobuf:"varint,8,opt,name=create_timestamp,json=createTimestamp,proto3" json:"create_timestamp,omitempty"`
}

func (m *SwapMaker) Reset()         { *m = SwapMaker{} }
func (m *SwapMaker) String() string { return proto.CompactTextString(m) }
func (*SwapMaker) ProtoMessage()    {}
func (*SwapMaker) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ab3ff4471e3e52b, []int{1}
}
func (m *SwapMaker) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SwapMaker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SwapMaker.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SwapMaker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapMaker.Merge(m, src)
}
func (m *SwapMaker) XXX_Size() int {
	return m.Size()
}
func (m *SwapMaker) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapMaker.DiscardUnknown(m)
}

var xxx_messageInfo_SwapMaker proto.InternalMessageInfo

func (m *SwapMaker) GetSourcePort() string {
	if m != nil {
		return m.SourcePort
	}
	return ""
}

func (m *SwapMaker) GetSourceChannel() string {
	if m != nil {
		return m.SourceChannel
	}
	return ""
}

func (m *SwapMaker) GetSellToken() types.Coin {
	if m != nil {
		return m.SellToken
	}
	return types.Coin{}
}

func (m *SwapMaker) GetBuyToken() types.Coin {
	if m != nil {
		return m.BuyToken
	}
	return types.Coin{}
}

func (m *SwapMaker) GetMakerAddress() string {
	if m != nil {
		return m.MakerAddress
	}
	return ""
}

func (m *SwapMaker) GetMakerReceivingAddress() string {
	if m != nil {
		return m.MakerReceivingAddress
	}
	return ""
}

func (m *SwapMaker) GetDesiredTaker() string {
	if m != nil {
		return m.DesiredTaker
	}
	return ""
}

func (m *SwapMaker) GetCreateTimestamp() int64 {
	if m != nil {
		return m.CreateTimestamp
	}
	return 0
}

type SwapTaker struct {
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// the tokens to be sell
	SellToken types.Coin `protobuf:"bytes,2,opt,name=sell_token,json=sellToken,proto3" json:"sell_token"`
	// the sender address
	TakerAddress string `protobuf:"bytes,3,opt,name=taker_address,json=takerAddress,proto3" json:"taker_address,omitempty" yaml:"taker_address"`
	// the sender's address on the destination chain
	TakerReceivingAddress string `protobuf:"bytes,4,opt,name=taker_receiving_address,json=takerReceivingAddress,proto3" json:"taker_receiving_address,omitempty" yaml:"taker_receiving_address"`
	CreateTimestamp       int64  `protobuf:"varint,5,opt,name=create_timestamp,json=createTimestamp,proto3" json:"create_timestamp,omitempty"`
}

func (m *SwapTaker) Reset()         { *m = SwapTaker{} }
func (m *SwapTaker) String() string { return proto.CompactTextString(m) }
func (*SwapTaker) ProtoMessage()    {}
func (*SwapTaker) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ab3ff4471e3e52b, []int{2}
}
func (m *SwapTaker) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SwapTaker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SwapTaker.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SwapTaker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapTaker.Merge(m, src)
}
func (m *SwapTaker) XXX_Size() int {
	return m.Size()
}
func (m *SwapTaker) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapTaker.DiscardUnknown(m)
}

var xxx_messageInfo_SwapTaker proto.InternalMessageInfo

func (m *SwapTaker) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *SwapTaker) GetSellToken() types.Coin {
	if m != nil {
		return m.SellToken
	}
	return types.Coin{}
}

func (m *SwapTaker) GetTakerAddress() string {
	if m != nil {
		return m.TakerAddress
	}
	return ""
}

func (m *SwapTaker) GetTakerReceivingAddress() string {
	if m != nil {
		return m.TakerReceivingAddress
	}
	return ""
}

func (m *SwapTaker) GetCreateTimestamp() int64 {
	if m != nil {
		return m.CreateTimestamp
	}
	return 0
}

type Order struct {
	Id                string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Maker             *MakeSwapMsg `protobuf:"bytes,2,opt,name=maker,proto3" json:"maker,omitempty"`
	Status            Status       `protobuf:"varint,3,opt,name=status,proto3,enum=ibc.applications.atomic_swap.v1.Status" json:"status,omitempty"`
	Path              string       `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Taker             *TakeSwapMsg `protobuf:"bytes,5,opt,name=taker,proto3" json:"taker,omitempty"`
	CancelTimestamp   uint64       `protobuf:"varint,6,opt,name=cancelTimestamp,proto3" json:"cancelTimestamp,omitempty"`
	CompleteTimestamp uint64       `protobuf:"varint,7,opt,name=completeTimestamp,proto3" json:"completeTimestamp,omitempty"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ab3ff4471e3e52b, []int{3}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Order.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return m.Size()
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetMaker() *MakeSwapMsg {
	if m != nil {
		return m.Maker
	}
	return nil
}

func (m *Order) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_INITIAL
}

func (m *Order) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Order) GetTaker() *TakeSwapMsg {
	if m != nil {
		return m.Taker
	}
	return nil
}

func (m *Order) GetCancelTimestamp() uint64 {
	if m != nil {
		return m.CancelTimestamp
	}
	return 0
}

func (m *Order) GetCompleteTimestamp() uint64 {
	if m != nil {
		return m.CompleteTimestamp
	}
	return 0
}

// Define the AtomicSwapPacketAcknowledgement union message.
type AtomicSwapPacketAcknowledgement struct {
	// Types that are valid to be assigned to Response:
	//	*AtomicSwapPacketAcknowledgement_Success
	//	*AtomicSwapPacketAcknowledgement_Error
	Response isAtomicSwapPacketAcknowledgement_Response `protobuf_oneof:"response"`
}

func (m *AtomicSwapPacketAcknowledgement) Reset()         { *m = AtomicSwapPacketAcknowledgement{} }
func (m *AtomicSwapPacketAcknowledgement) String() string { return proto.CompactTextString(m) }
func (*AtomicSwapPacketAcknowledgement) ProtoMessage()    {}
func (*AtomicSwapPacketAcknowledgement) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ab3ff4471e3e52b, []int{4}
}
func (m *AtomicSwapPacketAcknowledgement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AtomicSwapPacketAcknowledgement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AtomicSwapPacketAcknowledgement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AtomicSwapPacketAcknowledgement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AtomicSwapPacketAcknowledgement.Merge(m, src)
}
func (m *AtomicSwapPacketAcknowledgement) XXX_Size() int {
	return m.Size()
}
func (m *AtomicSwapPacketAcknowledgement) XXX_DiscardUnknown() {
	xxx_messageInfo_AtomicSwapPacketAcknowledgement.DiscardUnknown(m)
}

var xxx_messageInfo_AtomicSwapPacketAcknowledgement proto.InternalMessageInfo

type isAtomicSwapPacketAcknowledgement_Response interface {
	isAtomicSwapPacketAcknowledgement_Response()
	MarshalTo([]byte) (int, error)
	Size() int
}

type AtomicSwapPacketAcknowledgement_Success struct {
	Success *AtomicSwapPacketSuccess `protobuf:"bytes,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
}
type AtomicSwapPacketAcknowledgement_Error struct {
	Error *AtomicSwapPacketError `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (*AtomicSwapPacketAcknowledgement_Success) isAtomicSwapPacketAcknowledgement_Response() {}
func (*AtomicSwapPacketAcknowledgement_Error) isAtomicSwapPacketAcknowledgement_Response()   {}

func (m *AtomicSwapPacketAcknowledgement) GetResponse() isAtomicSwapPacketAcknowledgement_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *AtomicSwapPacketAcknowledgement) GetSuccess() *AtomicSwapPacketSuccess {
	if x, ok := m.GetResponse().(*AtomicSwapPacketAcknowledgement_Success); ok {
		return x.Success
	}
	return nil
}

func (m *AtomicSwapPacketAcknowledgement) GetError() *AtomicSwapPacketError {
	if x, ok := m.GetResponse().(*AtomicSwapPacketAcknowledgement_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AtomicSwapPacketAcknowledgement) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AtomicSwapPacketAcknowledgement_Success)(nil),
		(*AtomicSwapPacketAcknowledgement_Error)(nil),
	}
}

// Define the AtomicSwapPacketSuccess message.
type AtomicSwapPacketSuccess struct {
	resultBase64 string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *AtomicSwapPacketSuccess) Reset()         { *m = AtomicSwapPacketSuccess{} }
func (m *AtomicSwapPacketSuccess) String() string { return proto.CompactTextString(m) }
func (*AtomicSwapPacketSuccess) ProtoMessage()    {}
func (*AtomicSwapPacketSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ab3ff4471e3e52b, []int{5}
}
func (m *AtomicSwapPacketSuccess) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AtomicSwapPacketSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AtomicSwapPacketSuccess.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AtomicSwapPacketSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AtomicSwapPacketSuccess.Merge(m, src)
}
func (m *AtomicSwapPacketSuccess) XXX_Size() int {
	return m.Size()
}
func (m *AtomicSwapPacketSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_AtomicSwapPacketSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_AtomicSwapPacketSuccess proto.InternalMessageInfo

func (m *AtomicSwapPacketSuccess) GetresultBase64() string {
	if m != nil {
		return m.resultBase64
	}
	return ""
}

// Define the AtomicSwapPacketError message.
type AtomicSwapPacketError struct {
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *AtomicSwapPacketError) Reset()         { *m = AtomicSwapPacketError{} }
func (m *AtomicSwapPacketError) String() string { return proto.CompactTextString(m) }
func (*AtomicSwapPacketError) ProtoMessage()    {}
func (*AtomicSwapPacketError) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ab3ff4471e3e52b, []int{6}
}
func (m *AtomicSwapPacketError) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AtomicSwapPacketError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AtomicSwapPacketError.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AtomicSwapPacketError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AtomicSwapPacketError.Merge(m, src)
}
func (m *AtomicSwapPacketError) XXX_Size() int {
	return m.Size()
}
func (m *AtomicSwapPacketError) XXX_DiscardUnknown() {
	xxx_messageInfo_AtomicSwapPacketError.DiscardUnknown(m)
}

var xxx_messageInfo_AtomicSwapPacketError proto.InternalMessageInfo

func (m *AtomicSwapPacketError) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("ibc.applications.atomic_swap.v1.Status", Status_name, Status_value)
	proto.RegisterEnum("ibc.applications.atomic_swap.v1.FillStatus", FillStatus_name, FillStatus_value)
	proto.RegisterType((*Params)(nil), "ibc.applications.atomic_swap.v1.Params")
	proto.RegisterType((*SwapMaker)(nil), "ibc.applications.atomic_swap.v1.SwapMaker")
	proto.RegisterType((*SwapTaker)(nil), "ibc.applications.atomic_swap.v1.SwapTaker")
	proto.RegisterType((*Order)(nil), "ibc.applications.atomic_swap.v1.Order")
	proto.RegisterType((*AtomicSwapPacketAcknowledgement)(nil), "ibc.applications.atomic_swap.v1.AtomicSwapPacketAcknowledgement")
	proto.RegisterType((*AtomicSwapPacketSuccess)(nil), "ibc.applications.atomic_swap.v1.AtomicSwapPacketSuccess")
	proto.RegisterType((*AtomicSwapPacketError)(nil), "ibc.applications.atomic_swap.v1.AtomicSwapPacketError")
}

func init() {
	proto.RegisterFile("ibc/applications/atomic_swap/v1/swap.proto", fileDescriptor_7ab3ff4471e3e52b)
}

var fileDescriptor_7ab3ff4471e3e52b = []byte{
	// 935 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0x65, 0x49, 0x96, 0xc6, 0x92, 0xa3, 0x6c, 0xed, 0x5a, 0xce, 0x41, 0x32, 0xd8, 0x43,
	0x55, 0x23, 0x21, 0xe1, 0x24, 0x48, 0x9b, 0xa0, 0x69, 0x23, 0xa9, 0x32, 0x62, 0xc0, 0x91, 0x8d,
	0xb5, 0x2e, 0xcd, 0xa1, 0xc4, 0x8a, 0xdc, 0xca, 0x84, 0x49, 0x2e, 0xc1, 0x5d, 0xf9, 0xe7, 0xd4,
	0x57, 0xe8, 0x83, 0xf4, 0x41, 0x72, 0xe8, 0x21, 0x40, 0x2f, 0x3d, 0x09, 0x85, 0xfd, 0x00, 0x05,
	0xf4, 0x04, 0xc5, 0xee, 0x52, 0x2e, 0xa3, 0xd8, 0x70, 0x72, 0x92, 0x66, 0xbe, 0xf9, 0xbe, 0x1d,
	0x7e, 0x33, 0xe4, 0xc2, 0xb6, 0x3f, 0x72, 0x6d, 0x12, 0xc7, 0x81, 0xef, 0x12, 0xe1, 0xb3, 0x88,
	0xdb, 0x44, 0xb0, 0xd0, 0x77, 0x1d, 0x7e, 0x46, 0x62, 0xfb, 0x74, 0xc7, 0x96, 0xbf, 0x56, 0x9c,
	0x30, 0xc1, 0x50, 0xcb, 0x1f, 0xb9, 0x56, 0xb6, 0xd6, 0xca, 0xd4, 0x5a, 0xa7, 0x3b, 0x0f, 0xd6,
	0xc6, 0x6c, 0xcc, 0x54, 0xad, 0x2d, 0xff, 0x69, 0xda, 0x83, 0xa6, 0xcb, 0x78, 0xc8, 0xb8, 0x3d,
	0x22, 0x9c, 0xda, 0xa7, 0x3b, 0x23, 0x2a, 0xc8, 0x8e, 0xed, 0x32, 0x3f, 0x4a, 0xf1, 0xf6, 0x5d,
	0x2d, 0x88, 0x73, 0x5d, 0x69, 0xfe, 0x06, 0xa5, 0x43, 0x92, 0x90, 0x90, 0xa3, 0x17, 0x50, 0x95,
	0xa8, 0x43, 0x23, 0x32, 0x0a, 0xa8, 0xd7, 0x30, 0xb6, 0x8c, 0x76, 0xb9, 0xbb, 0x31, 0x9b, 0xb6,
	0xbe, 0xb8, 0x20, 0x61, 0xf0, 0xc2, 0xcc, 0xa2, 0x26, 0x5e, 0x91, 0x61, 0x5f, 0x47, 0xe8, 0x39,
	0x54, 0x43, 0x72, 0xee, 0xfc, 0x4a, 0xa9, 0x93, 0x10, 0x41, 0x1b, 0xf9, 0x2d, 0xa3, 0x5d, 0xcb,
	0x72, 0xb3, 0xa8, 0x89, 0x21, 0x24, 0xe7, 0xbb, 0x94, 0x62, 0x19, 0xfc, 0xbb, 0x04, 0x95, 0xa3,
	0x33, 0x12, 0xbf, 0x21, 0x27, 0x34, 0x41, 0xdf, 0xc2, 0x0a, 0x67, 0x93, 0xc4, 0xa5, 0x4e, 0xcc,
	0x12, 0xa1, 0x7a, 0xa8, 0x74, 0xbf, 0x9c, 0x4d, 0x5b, 0x28, 0xed, 0xe1, 0x7f, 0xd0, 0xc4, 0xa0,
	0xa3, 0x43, 0x96, 0x08, 0xf4, 0x0a, 0x56, 0x53, 0xcc, 0x3d, 0x26, 0x51, 0x44, 0x03, 0xd5, 0x43,
	0xa5, 0xbb, 0x39, 0x9b, 0xb6, 0xd6, 0x3f, 0xe0, 0xa6, 0xb8, 0x89, 0x6b, 0x3a, 0xd1, 0xd3, 0x31,
	0xfa, 0x01, 0x80, 0xd3, 0x20, 0x70, 0x04, 0x3b, 0xa1, 0x51, 0x63, 0x69, 0xcb, 0x68, 0xaf, 0x3c,
	0xde, 0xb4, 0xb4, 0xd1, 0x96, 0x34, 0xda, 0x4a, 0x8d, 0xb6, 0x7a, 0xcc, 0x8f, 0xba, 0x85, 0x77,
	0xd3, 0x56, 0x0e, 0x57, 0x24, 0x65, 0x28, 0x19, 0xe8, 0x7b, 0xa8, 0x8c, 0x26, 0x17, 0x29, 0xbd,
	0xf0, 0x69, 0xf4, 0xf2, 0x68, 0x72, 0xa1, 0xd9, 0x2f, 0xa1, 0x16, 0x4a, 0x07, 0x1c, 0xe2, 0x79,
	0x09, 0xe5, 0xbc, 0x51, 0x54, 0xed, 0x37, 0x66, 0xd3, 0xd6, 0xda, 0xdc, 0xc2, 0x0c, 0x6c, 0xe2,
	0xaa, 0x8a, 0x3b, 0x3a, 0x44, 0x6f, 0x61, 0x43, 0xe3, 0x09, 0x75, 0xa9, 0x7f, 0xea, 0x47, 0xe3,
	0x6b, 0xa1, 0x92, 0x12, 0x32, 0x67, 0xd3, 0x56, 0x33, 0x2b, 0xf4, 0x51, 0xa1, 0x89, 0xd7, 0x15,
	0x82, 0xe7, 0xc0, 0x5c, 0xfb, 0x2b, 0xa8, 0x79, 0x94, 0xfb, 0x09, 0xf5, 0x1c, 0x21, 0x0b, 0x1a,
	0xcb, 0x52, 0x11, 0x57, 0xd3, 0xe4, 0x50, 0x0d, 0xee, 0x1b, 0xa8, 0xbb, 0x09, 0x25, 0x82, 0x3a,
	0xc2, 0x0f, 0x29, 0x17, 0x24, 0x8c, 0x1b, 0xe5, 0x2d, 0xa3, 0xbd, 0x84, 0xef, 0xe9, 0xfc, 0x70,
	0x9e, 0x36, 0xff, 0xc8, 0xeb, 0x89, 0x6b, 0xe2, 0x26, 0x94, 0x59, 0xe2, 0xd1, 0xc4, 0xf1, 0xf5,
	0xca, 0x55, 0xf0, 0xb2, 0x8a, 0xf7, 0xbc, 0x85, 0x89, 0xe4, 0x3f, 0x7b, 0x22, 0x2f, 0xa1, 0x26,
	0x3e, 0xf0, 0x74, 0x69, 0xd1, 0x53, 0xb1, 0xe0, 0xa9, 0x58, 0xf0, 0x54, 0xdc, 0xe2, 0x69, 0x61,
	0xd1, 0x53, 0x71, 0xab, 0xa7, 0xe2, 0x46, 0x4f, 0x6f, 0xb2, 0xab, 0x78, 0xb3, 0x5d, 0x7f, 0xe6,
	0xa1, 0x78, 0x20, 0x1d, 0x41, 0xab, 0x90, 0xbf, 0x36, 0x29, 0xef, 0x7b, 0xa8, 0x0b, 0x45, 0x35,
	0xb1, 0xd4, 0x9a, 0x87, 0xd6, 0x1d, 0x1f, 0x13, 0x4b, 0xbe, 0x63, 0xea, 0x5d, 0xe3, 0x63, 0xac,
	0xa9, 0xe8, 0x47, 0x28, 0x71, 0x41, 0xc4, 0x44, 0x9b, 0xb3, 0xfa, 0xf8, 0xeb, 0x3b, 0x45, 0x8e,
	0x54, 0x39, 0x4e, 0x69, 0x08, 0x41, 0x21, 0x26, 0xe2, 0x58, 0x5b, 0x82, 0xd5, 0x7f, 0xd9, 0x98,
	0xde, 0x94, 0xe2, 0x27, 0x36, 0x36, 0xcc, 0x36, 0xa6, 0xa8, 0xa8, 0x0d, 0xf7, 0x5c, 0x12, 0xb9,
	0x34, 0xb8, 0x76, 0x42, 0x6d, 0x72, 0x01, 0x2f, 0xa6, 0xd1, 0x43, 0xb8, 0xef, 0xb2, 0x30, 0x0e,
	0x68, 0xc6, 0x35, 0xb5, 0xa3, 0x05, 0xfc, 0x31, 0x60, 0xfe, 0x65, 0x40, 0xab, 0xa3, 0x4e, 0x97,
	0x07, 0x1e, 0x12, 0xf7, 0x84, 0x8a, 0x8e, 0x7b, 0x12, 0xb1, 0xb3, 0x80, 0x7a, 0x63, 0x1a, 0xd2,
	0x48, 0xa0, 0x21, 0x2c, 0xf3, 0x89, 0xeb, 0xca, 0x49, 0x1b, 0xea, 0x09, 0xbe, 0xbb, 0xf3, 0x09,
	0x16, 0x25, 0x8f, 0x34, 0xff, 0x75, 0x0e, 0xcf, 0xa5, 0xd0, 0x00, 0x8a, 0x34, 0x49, 0xd8, 0x7c,
	0x5c, 0xcf, 0x3e, 0x5b, 0xb3, 0x2f, 0xd9, 0xaf, 0x73, 0x58, 0xcb, 0x74, 0x01, 0xca, 0x09, 0xe5,
	0x31, 0x8b, 0x38, 0x35, 0x7b, 0xb0, 0x71, 0x4b, 0x07, 0xa8, 0x0d, 0xa5, 0x84, 0xf2, 0x49, 0x30,
	0xff, 0x9a, 0xd6, 0x2f, 0xa7, 0xad, 0xaa, 0xce, 0x74, 0x09, 0xa7, 0xcf, 0x9e, 0xe2, 0x14, 0x37,
	0x1f, 0xc1, 0xfa, 0x8d, 0x47, 0xa2, 0xb5, 0x79, 0xe7, 0x7a, 0xf7, 0x74, 0xb0, 0xfd, 0x1c, 0x4a,
	0x7a, 0x17, 0xd0, 0x0a, 0x2c, 0xef, 0x0d, 0xf6, 0x86, 0x7b, 0x9d, 0xfd, 0x7a, 0x0e, 0x95, 0xa1,
	0x70, 0xf4, 0xf3, 0xa0, 0x57, 0x37, 0x10, 0x40, 0xa9, 0xd7, 0x19, 0xf4, 0xfa, 0xfb, 0xf5, 0x3c,
	0xaa, 0x42, 0xb9, 0x77, 0xf0, 0xe6, 0x70, 0xbf, 0x3f, 0xec, 0xd7, 0x97, 0xb6, 0x5f, 0x01, 0xec,
	0xfa, 0x41, 0x90, 0xd2, 0x6b, 0x50, 0x19, 0x1c, 0x0c, 0xfa, 0xce, 0xee, 0xde, 0xbe, 0x14, 0xa8,
	0x43, 0xf5, 0xb0, 0x83, 0xa5, 0x9a, 0xce, 0x18, 0xe8, 0x3e, 0xd4, 0xe6, 0x64, 0x9d, 0xca, 0x77,
	0x7f, 0x79, 0x77, 0xd9, 0x34, 0xde, 0x5f, 0x36, 0x8d, 0x7f, 0x2e, 0x9b, 0xc6, 0xef, 0x57, 0xcd,
	0xdc, 0xfb, 0xab, 0x66, 0xee, 0xef, 0xab, 0x66, 0xee, 0xed, 0x4f, 0x63, 0x5f, 0x1c, 0x4f, 0x46,
	0x96, 0xcb, 0x42, 0x9b, 0xfb, 0x1e, 0x55, 0xf7, 0x9c, 0xcb, 0x02, 0xdb, 0x1f, 0xb9, 0xfa, 0xfa,
	0x7b, 0x6a, 0x87, 0xcc, 0x9b, 0x04, 0x94, 0xcb, 0x2b, 0x92, 0xdb, 0x4f, 0x76, 0x1e, 0x65, 0x6f,
	0x47, 0x71, 0x11, 0x53, 0x3e, 0x2a, 0x29, 0xda, 0x93, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x71,
	0x8c, 0xc8, 0xf6, 0xcd, 0x07, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxFeeRate != 0 {
		i = encodeVarintSwap(dAtA, i, uint64(m.MaxFeeRate))
		i--
		dAtA[i] = 0x10
	}
	if m.SwapEnabled {
		i--
		if m.SwapEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SwapMaker) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SwapMaker) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SwapMaker) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreateTimestamp != 0 {
		i = encodeVarintSwap(dAtA, i, uint64(m.CreateTimestamp))
		i--
		dAtA[i] = 0x40
	}
	if len(m.DesiredTaker) > 0 {
		i -= len(m.DesiredTaker)
		copy(dAtA[i:], m.DesiredTaker)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.DesiredTaker)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.MakerReceivingAddress) > 0 {
		i -= len(m.MakerReceivingAddress)
		copy(dAtA[i:], m.MakerReceivingAddress)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.MakerReceivingAddress)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.MakerAddress) > 0 {
		i -= len(m.MakerAddress)
		copy(dAtA[i:], m.MakerAddress)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.MakerAddress)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size, err := m.BuyToken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSwap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.SellToken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSwap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.SourceChannel) > 0 {
		i -= len(m.SourceChannel)
		copy(dAtA[i:], m.SourceChannel)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.SourceChannel)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SourcePort) > 0 {
		i -= len(m.SourcePort)
		copy(dAtA[i:], m.SourcePort)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.SourcePort)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SwapTaker) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SwapTaker) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SwapTaker) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreateTimestamp != 0 {
		i = encodeVarintSwap(dAtA, i, uint64(m.CreateTimestamp))
		i--
		dAtA[i] = 0x28
	}
	if len(m.TakerReceivingAddress) > 0 {
		i -= len(m.TakerReceivingAddress)
		copy(dAtA[i:], m.TakerReceivingAddress)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.TakerReceivingAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TakerAddress) > 0 {
		i -= len(m.TakerAddress)
		copy(dAtA[i:], m.TakerAddress)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.TakerAddress)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.SellToken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSwap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.OrderId) > 0 {
		i -= len(m.OrderId)
		copy(dAtA[i:], m.OrderId)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.OrderId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Order) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Order) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Order) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CompleteTimestamp != 0 {
		i = encodeVarintSwap(dAtA, i, uint64(m.CompleteTimestamp))
		i--
		dAtA[i] = 0x38
	}
	if m.CancelTimestamp != 0 {
		i = encodeVarintSwap(dAtA, i, uint64(m.CancelTimestamp))
		i--
		dAtA[i] = 0x30
	}
	if m.Taker != nil {
		{
			size, err := m.Taker.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSwap(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Path) > 0 {
		i -= len(m.Path)
		copy(dAtA[i:], m.Path)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.Path)))
		i--
		dAtA[i] = 0x22
	}
	if m.Status != 0 {
		i = encodeVarintSwap(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	if m.Maker != nil {
		{
			size, err := m.Maker.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSwap(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AtomicSwapPacketAcknowledgement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AtomicSwapPacketAcknowledgement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AtomicSwapPacketAcknowledgement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Response != nil {
		{
			size := m.Response.Size()
			i -= size
			if _, err := m.Response.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *AtomicSwapPacketAcknowledgement_Success) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AtomicSwapPacketAcknowledgement_Success) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Success != nil {
		{
			size, err := m.Success.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSwap(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *AtomicSwapPacketAcknowledgement_Error) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AtomicSwapPacketAcknowledgement_Error) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Error != nil {
		{
			size, err := m.Error.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSwap(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *AtomicSwapPacketSuccess) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AtomicSwapPacketSuccess) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AtomicSwapPacketSuccess) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.resultBase64) > 0 {
		i -= len(m.resultBase64)
		copy(dAtA[i:], m.resultBase64)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.resultBase64)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AtomicSwapPacketError) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AtomicSwapPacketError) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AtomicSwapPacketError) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Error) > 0 {
		i -= len(m.Error)
		copy(dAtA[i:], m.Error)
		i = encodeVarintSwap(dAtA, i, uint64(len(m.Error)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSwap(dAtA []byte, offset int, v uint64) int {
	offset -= sovSwap(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SwapEnabled {
		n += 2
	}
	if m.MaxFeeRate != 0 {
		n += 1 + sovSwap(uint64(m.MaxFeeRate))
	}
	return n
}

func (m *SwapMaker) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SourcePort)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	l = len(m.SourceChannel)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	l = m.SellToken.Size()
	n += 1 + l + sovSwap(uint64(l))
	l = m.BuyToken.Size()
	n += 1 + l + sovSwap(uint64(l))
	l = len(m.MakerAddress)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	l = len(m.MakerReceivingAddress)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	l = len(m.DesiredTaker)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	if m.CreateTimestamp != 0 {
		n += 1 + sovSwap(uint64(m.CreateTimestamp))
	}
	return n
}

func (m *SwapTaker) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrderId)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	l = m.SellToken.Size()
	n += 1 + l + sovSwap(uint64(l))
	l = len(m.TakerAddress)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	l = len(m.TakerReceivingAddress)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	if m.CreateTimestamp != 0 {
		n += 1 + sovSwap(uint64(m.CreateTimestamp))
	}
	return n
}

func (m *Order) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	if m.Maker != nil {
		l = m.Maker.Size()
		n += 1 + l + sovSwap(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovSwap(uint64(m.Status))
	}
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	if m.Taker != nil {
		l = m.Taker.Size()
		n += 1 + l + sovSwap(uint64(l))
	}
	if m.CancelTimestamp != 0 {
		n += 1 + sovSwap(uint64(m.CancelTimestamp))
	}
	if m.CompleteTimestamp != 0 {
		n += 1 + sovSwap(uint64(m.CompleteTimestamp))
	}
	return n
}

func (m *AtomicSwapPacketAcknowledgement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Response != nil {
		n += m.Response.Size()
	}
	return n
}

func (m *AtomicSwapPacketAcknowledgement_Success) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success != nil {
		l = m.Success.Size()
		n += 1 + l + sovSwap(uint64(l))
	}
	return n
}
func (m *AtomicSwapPacketAcknowledgement_Error) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Error != nil {
		l = m.Error.Size()
		n += 1 + l + sovSwap(uint64(l))
	}
	return n
}
func (m *AtomicSwapPacketSuccess) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.resultBase64)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	return n
}

func (m *AtomicSwapPacketError) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovSwap(uint64(l))
	}
	return n
}

func sovSwap(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSwap(x uint64) (n int) {
	return sovSwap(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSwap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SwapEnabled = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxFeeRate", wireType)
			}
			m.MaxFeeRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxFeeRate |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSwap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSwap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SwapMaker) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSwap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SwapMaker: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SwapMaker: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourcePort", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourcePort = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SellToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BuyToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MakerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerReceivingAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MakerReceivingAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DesiredTaker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DesiredTaker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateTimestamp", wireType)
			}
			m.CreateTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreateTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSwap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSwap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SwapTaker) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSwap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SwapTaker: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SwapTaker: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SellToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TakerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerReceivingAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TakerReceivingAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateTimestamp", wireType)
			}
			m.CreateTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreateTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSwap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSwap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Order) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSwap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Order: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Order: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Maker", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Maker == nil {
				m.Maker = &MakeSwapMsg{}
			}
			if err := m.Maker.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Taker", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Taker == nil {
				m.Taker = &TakeSwapMsg{}
			}
			if err := m.Taker.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CancelTimestamp", wireType)
			}
			m.CancelTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CancelTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompleteTimestamp", wireType)
			}
			m.CompleteTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompleteTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSwap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSwap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AtomicSwapPacketAcknowledgement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSwap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AtomicSwapPacketAcknowledgement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AtomicSwapPacketAcknowledgement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &AtomicSwapPacketSuccess{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Response = &AtomicSwapPacketAcknowledgement_Success{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &AtomicSwapPacketError{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Response = &AtomicSwapPacketAcknowledgement_Error{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSwap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSwap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AtomicSwapPacketSuccess) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSwap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AtomicSwapPacketSuccess: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AtomicSwapPacketSuccess: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field resultBase64", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.resultBase64 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSwap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSwap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AtomicSwapPacketError) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSwap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AtomicSwapPacketError: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AtomicSwapPacketError: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSwap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSwap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSwap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSwap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSwap(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSwap
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSwap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSwap
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSwap
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSwap
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSwap        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSwap          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSwap = fmt.Errorf("proto: unexpected end of group")
)
